/**
 * Shared seed helpers — file I/O, tool-seed loader, schema merger, bundled
 * template copier. All `_seed*` per-agent modules depend on these. Extracted
 * from `extension.ts` (Clean Architecture · SRP).
 *
 * Pure side-effect helpers — no VS Code API, no `vscode` import.
 */

import * as fs from 'fs';
import * as path from 'path';

/* v2.89.62 — 11개 Python 도구 + 11개 README 를 assets/tool-seeds/<agent>/<tool>.{py,md} 로 분리.
   각 _seed* 함수에서 lazy load. assets/tool-seeds/secretary/telegram_setup.py 같은 형태. */
const _TOOL_SEEDS_DIR = path.join(__dirname, '..', 'assets', 'tool-seeds');
const _toolSeedCache = new Map<string, string>();

export function _loadToolSeed(rel: string): string {
    let cached = _toolSeedCache.get(rel);
    if (cached !== undefined) return cached;
    try {
        cached = fs.readFileSync(path.join(_TOOL_SEEDS_DIR, rel), 'utf-8');
    } catch (e: any) {
        console.error(`[Connect AI] tool seed 로드 실패 ${rel}:`, e?.message || e);
        cached = '';
    }
    _toolSeedCache.set(rel, cached);
    return cached;
}

export function _seedFile(p: string, content: string) {
  if (fs.existsSync(p)) return;
  fs.writeFileSync(p, content);
}

/* Like _seedFile but force-overwrites if the existing file is missing a
   sentinel string. Use for autogenerated tool scripts when we ship a new
   version that needs to replace the old one — sentinel changes per version. */
export function _seedFileForceUpgrade(p: string, content: string, sentinel: string) {
  if (!fs.existsSync(p)) {
    fs.writeFileSync(p, content);
    return;
  }
  try {
    const cur = fs.readFileSync(p, 'utf-8');
    if (!cur.includes(sentinel)) {
      fs.writeFileSync(p, content);
    }
  } catch { /* ignore */ }
}

/* JSON 시드 파일에 새 _schema를 머지. 사용자가 입력한 값은 절대 건드리지 않고,
   _schema만 항상 최신으로 갱신. fresh에 새로 추가된 키는 빈 값으로 추가하고,
   existing에만 있는 키도 보존 (예: 나중에 OAuth flow가 추가한 토큰). */
export function _mergeSchemaIntoJson(p: string, freshJson: string) {
  if (!fs.existsSync(p)) {
    fs.writeFileSync(p, freshJson);
    return;
  }
  try {
    const fresh = JSON.parse(freshJson);
    const existing = JSON.parse(fs.readFileSync(p, 'utf-8') || '{}');
    /* 1) existing의 모든 키 그대로 보존 (OAuth 토큰처럼 동적으로 추가된 값 포함) */
    const merged: Record<string, any> = { ...existing };
    /* 2) fresh에만 있는 새 키는 빈 값으로 추가 */
    for (const k of Object.keys(fresh)) {
      if (k === '_schema') continue;
      if (!(k in merged)) merged[k] = fresh[k];
    }
    /* 3) _schema는 항상 최신 fresh로 덮어쓰기 (사용자가 편집하지 않는 메타) */
    merged['_schema'] = fresh['_schema'];
    fs.writeFileSync(p, JSON.stringify(merged, null, 2));
  } catch {
    fs.writeFileSync(p, freshJson);
  }
}

export function _copyDirRecursive(src: string, dst: string) {
  fs.mkdirSync(dst, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const s = path.join(src, entry.name);
    const d = path.join(dst, entry.name);
    if (entry.isDirectory()) _copyDirRecursive(s, d);
    else fs.copyFileSync(s, d);
  }
}

export function _seedBundledTemplates(agentId: string, targetDir: string) {
  try {
    const seedRoot = path.join(__dirname, '..', 'assets', 'brain-seeds', '40_템플릿', agentId);
    if (!fs.existsSync(seedRoot)) return;
    fs.mkdirSync(targetDir, { recursive: true });
    const templates = fs.readdirSync(seedRoot, { withFileTypes: true }).filter(e => e.isDirectory());
    for (const tpl of templates) {
      const src = path.join(seedRoot, tpl.name);
      const dst = path.join(targetDir, tpl.name);
      if (fs.existsSync(dst)) continue;  /* 이미 있으면 사용자 편집 보호 */
      _copyDirRecursive(src, dst);
    }
  } catch (err) {
    console.error('[Connect AI] 템플릿 시드 실패:', err);
  }
}
